## Explanation of Groups ##

#Groups names for selecting are: 'M0', 'M1', 'M2', 'Cardiac', 'SIS', 'UMB', 'Card_M0', 'Card_M1', 'Card_M2', 'SIS_M0', 'SIS_M1', 'SIS_M2', 'UBM_M0', 'UBM_M1', 'UBM_M2'

#Feature groups are: 
#morphological_measurments = ['CellArea', 'cellbody_area', 'Cell_Elongation', 'cell_full_length', 'cell_half_width', 'Cell_length_by_area', 'Cell_width_by_area', 'NucleusArea', 'Nuc_Elongation', 'Nuc_full_length', 'Nuc_half_width', 'Nuc_Roundness', 'roundness', 'body_roundness', 'percentProtrusion', 'protrusion_extent', 'total_protrusionarea', 'mean_protrusionarea', 'number_protrusions', 'skeleton_area', 'skeleton_node_count', 'skeletonareapercent']
#intensity_measurements = ['cytointensityActin', 'cytointensityTubulin', 'CytoIntensityH', 'CytoNonMembraneIntensityActin', 'CytoNonMembraneIntensityTubulin', 'MembraneIntensityActin', 'MembraneIntensityTubulin', 'NucIntensityActin', 'NucIntensityTubulin', 'NucIntensityH', 'ProtrusionIntensityActin', 'ProtrusionIntensityTubulin', 'ringIntensityActin', 'ringIntensityTubulin', 'RingIntensityH', 'WholeCellIntensityActin', 'WholeCellIntensityTubulin', 'WholeCellIntensityH']
#spatial_texture = ['centers_area', 'centers_distance', 'cytoplasm_area', 'GaborMax1_Actin', 'GaborMin1_Actin', 'HarConCellAct', 'HarConCytoTub', 'HarConMembAct', 'HarCorrCellAct', 'HarCorrCytoTub', 'HarCorrMembAct', 'HarHomCellAct', 'HarHomCytoTub', 'HarHomMembAct', 'HarSVCellAct', 'HarSVCytoTub', 'HarSVMembAct', 'logNucbyRingActin', 'logNucbyRingTubulin', 'mean_prlength', 'MembranebyCytoOnlyActin', 'MembranebyCytoOnlyTubulin', 'NucbyCytoArea', 'NucbyRingActin', 'NucbyRingTubulin', 'NucPlusRingActin', 'NucPlusRingTubulin', 'RingbyCytoActin', 'RingbyCytoTubulin', 'ringregion_area']
#SER_analysis = ['SERBrightCellAct', 'SERBrightCytoTub', 'SERBrightMembAct', 'SERBrightNuc', 'SERDarkCellAct', 'SERDarkCytoTub', 'SERDarkMembAct', 'SERDarkNuc', 'SEREdgeCellAct', 'SEREdgeCytoTub', 'SEREdgeMembAct', 'SEREdgeNuc', 'SERHoleCellAct', 'SERHoleCytoTub', 'SERHoleMembAct', 'SERHoleNuc', 'SERRidgeCellAct', 'SERRidgeCytoTub', 'SERRidgeMembAct', 'SERRidgeNuc', 'SERSaddleCellAct', 'SERSaddleCytoTub', 'SERSaddleMembAct', 'SERSaddleNuc', 'SERSpotCellAct', 'SERSpotCytoTub', 'SERSpotMembAct', 'SERSpotNuc', 'SERValleyCellAct', 'SERValleyCytoTub', 'SERValleyMembAct', 'SERValleyNuc']
